server:
  port: 8081

inventory:
  url: "http://localhost:8082"

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/order_service
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: order-placed


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
    instances:
      inventory:
        base-config: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      inventory:
        base-config: default

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
    instances:
      inventory:
        base-config: default

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs




