server:
  port: 8082

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inventory_service
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: none
