server:
  port: 8082

services:
  auth-service-url: http://localhost:8080

app:
  internal-api-secret: ${INTERNAL_API_SECRET}


spring:
  application:
    name: spotify-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka